---
# tasks file for ansible-role-cuda
- name: Trust packaging key for CUDA repositories
  apt_key:
    data: "{{ lookup('file', 'files/cuda_packaging_key.asc') }}"
    id: "{{ cuda_packaging_key_id }}"
    state: present

- name: Configure CUDA repository for apt-based systems
  apt_repository:
    repo: "deb {{ cuda_repo_url }}/{{ cuda_repo_subfolder }}/x86_64 /"
    filename: cuda
    state: present

- name: Install CUDA and related packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cuda_packages }}"

- name: Determine what version of CUDA is installed
  shell: "dpkg-query --showformat='${Version}' --show cuda | cut -d. -f1-2"
  register: __cuda_dpkg_query
  changed_when: false

- set_fact: "__cuda_version={{ __cuda_dpkg_query.stdout_lines[0] }}"

- name: Add CUDA paths to user environments
  template:
    src: cuda.sh.j2
    dest: /etc/profile.d/cuda.sh
    backup: yes
    mode: 0755
