---
# tasks file for ansible-role-cuda
- name: Trust packaging key for CUDA repositories
  apt_key:
    data: "{{ lookup('file', 'files/cuda_packaging_key.asc') }}"
    id: "{{ cuda_packaging_key_id }}"
    state: present

- name: Configure CUDA repository for apt-based systems
  apt_repository:
    repo: "deb {{ cuda_repo_url }}/{{ cuda_repo_subfolder }}/x86_64 /"
    filename: cuda
    state: present

- name: Install CUDA and related packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ cuda_packages }}"
